### ISSUE TITLE
Trouble detecting mike

### ISSUE THREAD

**Issue by guiniol** [crmarsh/discord-linux-bugs#22]
Hello,

Just downloaded Discord, and first time user.
I think my microphone is not being detected properly. I selected the "default" device, but when I try to adjust the input sensitivity, no input is ever detected (it works properly in the browser). The other options all seem to be output devices.
Additionnaly, if I unplug the mike, no warning is shown (though the "show warning when not detecting audio from mike" button is checked).
I use alsa for the sound in my setup.

I tried running with --debug, but didn't see anything useful.

Cheers!

**Comment by crmarsh** [comment]
I'm not sure if `--debug` does anything. We're going to upgrade webrtc versions pretty soon, maybe whatever this is is fixed in there.

**Comment by guiniol** [comment]
OK. I'll wait for the next update. Keep up the good work.

**Comment by crmarsh** [comment]
We are on a newer webrtc, can you check if it is still having this problem for you in 0.0.7?

**Comment by guiniol** [comment]
It still doesn't seem to work, but I still only have the input sensitivity bar to check.
Is a feature to test the mike in the works?

**Comment by NEXUS2345** [comment]
I am also seeing this issue on Linux Mint 18 Cinnamon. Latest updates installed, on version 0.0.9. Web app works fine. The mic is an audio jack one connected to my motherboard's built in audio (Realtek codec).
